"use client";
import dynamic from "next/dynamic";
import {useCallback,useRef,useState,type FormEvent} from "react";
const AreaMap=dynamic(()=>import("./area-map"),{ssr:false});
type Area={name:string;lat:number;lng:number};
export default function AddBarangay({areas,onSaved,onClose}:{areas:Area[];onSaved:(area:Area)=>void;onClose:()=>void}){
 const [point,setPoint]=useState<{lat:number;lng:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const lock=useRef(false);
 const pick=useCallback((lat:number,lng:number)=>setPoint({lat,lng}),[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;if(!point){setError("Click the map to choose the barangay location.");return;}const f=new FormData(e.currentTarget);lock.current=true;setBusy(true);setError("");try{const response=await fetch("/api/areas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barangay:f.get("barangay"),city:f.get("city"),province:f.get("province"),...point})});const data=await response.json();if(!response.ok)throw new Error(data.error);onSaved(data.area);}catch(e){setError(e instanceof Error?e.message:"Could not save barangay.");}finally{lock.current=false;setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-barangay-title"><div className="panel-heading"><h2 id="add-barangay-title">Add barangay</h2><button className="icon-button" aria-label="Close" disabled={busy} onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label className="field">Barangay name<input name="barangay" required maxLength={80}/></label><label className="field">City / municipality<input name="city" required maxLength={80}/></label><label className="field">Province<input name="province" required maxLength={80}/></label></div><p>Zoom or move the map, then click the barangay location.</p><AreaMap areas={areas} onPick={pick}/><p>{point?`Selected: ${point.lat.toFixed(5)}, ${point.lng.toFixed(5)}`:"No location selected yet."}</p><p className="map-note">New screenings go to Demo City Hospital. The circle marks your selected point, not an official boundary. Barangays are saved in the shared database.</p>{error&&<p role="alert">{error}</p>}<button className="primary" type="submit" disabled={busy}>{busy?"Saving...":"Save barangay"}</button></form></section></div>;
}
