"use client";
import {useState} from "react";
import {RED_FLAG_LABELS,waistAboveReference,screeningMetrics,type Case} from "../lib/workflow";
const answers=["Not assessed","No","Yes"];
function Choice({name,label,options=answers}:{name:string;label:string;options?:string[]}){return <label className="field">{label}<select name={name}>{options.map(v=><option key={v}>{v}</option>)}</select></label>;}
export function RedFlagFields(){const [flags,setFlags]=useState<Record<string,string>>({});const urgent=Object.values(flags).includes("Yes");return <fieldset className="assessment-section"><legend>Immediate symptoms</legend><p>Record each answer. Do not delay immediate clinical care to finish this form.</p><div className="form-grid">{Object.entries(RED_FLAG_LABELS).map(([key,label])=><label className="field" key={key}>{label}<select name={`red_${key}`} value={flags[key]||"Not assessed"} onChange={e=>setFlags(v=>({...v,[key]:e.target.value}))}>{answers.map(v=><option key={v}>{v}</option>)}</select></label>)}</div>{urgent&&<div className="connection-warning" role="alert"><strong>Immediate clinical assessment needed.</strong><p>Contact the responsible physician / emergency service under your local protocol. Saving this record does not complete that handoff.</p><label className="field">Immediate action taken or requested<textarea name="immediateAction" required maxLength={500} placeholder="Record who was contacted and the handoff action."/></label></div>}</fieldset>;}
export function ExpandedFields(){const [initialTime]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));return <>
<fieldset className="assessment-section"><legend>Demographic profile — adult assessment (20+)</legend><div className="form-grid"><label className="field">Assessment date and time<input name="assessmentDate" type="datetime-local" required defaultValue={initialTime}/></label><Choice name="sex" label="Sex" options={["Not recorded","Male","Female"]}/><Choice name="civilStatus" label="Civil status" options={["Not recorded","Single","Married","Widowed","Other"]}/><label className="field">Address<input name="address" maxLength={500}/></label><Choice name="employment" label="Employment" options={["Not recorded","Employed","Self-employed","Unemployed","Retired"]}/></div></fieldset>
<fieldset className="assessment-section"><legend>Medical and family history</legend><p>Check known conditions. Mark assessed only when this was asked.</p><label className="assessment-check"><input name="conditionsAssessed" type="checkbox"/>Patient history assessed</label><div className="assessment-options">{["Hypertension","Diabetes","Asthma","Cancer","Kidney disease"].map(v=><label className="assessment-check" key={v}><input name="conditions" type="checkbox" value={v}/>{v}</label>)}</div><label className="assessment-check"><input name="familyAssessed" type="checkbox"/>First-degree family history assessed</label><div className="assessment-options">{["Stroke","Heart attack","Diabetes","Hypertension","Kidney disease"].map(v=><label className="assessment-check" key={v}><input name="familyHistory" type="checkbox" value={v}/>{v}</label>)}</div></fieldset>
<fieldset className="assessment-section"><legend>Lifestyle</legend><div className="form-grid"><Choice name="tobacco" label="Tobacco use" options={["Not assessed","Never used","Secondhand smoke exposure","Former smoker","Current smoker"]}/><Choice name="alcohol" label="Drinks alcohol?"/><Choice name="binge" label="5+ drinks (men) / 4+ (women) in one sitting?"/><Choice name="exercise" label="At least 2.5 hours of moderate exercise weekly?"/><Choice name="nutrition" label="High intake of fatty/salty foods or sugary drinks?"/></div></fieldset>
<fieldset className="assessment-section"><legend>Measurements</legend><p>Record at least two BP readings. The average is calculated automatically. Leave unavailable body measurements blank.</p><div className="form-grid">{[2,3].map(n=><div key={n}><label className="field">BP {n}: top number<input name={`systolic${n}`} type="number" min={1} required={n===2}/></label><label className="field">BP {n}: bottom number<input name={`diastolic${n}`} type="number" min={1} required={n===2}/></label><label className="field">BP {n}: measurement time<input name={`bpTime${n}`} type="datetime-local" defaultValue={initialTime} required={n===2}/></label></div>)}{[["heightCm","Height (cm)"],["weightKg","Weight (kg)"],["waistCm","Waist circumference (cm)"]].map(([name,label])=><label className="field" key={name}>{label}<input name={name} type="number" min={0.1} step="any"/></label>)}</div></fieldset></>;}
export function AssessmentDetails({patient:c}:{patient:Case}){const s=c.screening,a=s?.assessment,m=screeningMetrics(c);return <div className="documents"><h3>Assessment details</h3><p><strong>BP average:</strong> {m.systolic}/{m.diastolic} mmHg ({m.bpCount} recorded reading{m.bpCount===1?"":"s"})</p>{s?.redFlags&&<><p><strong>Immediate symptoms:</strong></p>{Object.entries(s.redFlags).map(([key,value])=><p key={key}>{RED_FLAG_LABELS[key as keyof typeof RED_FLAG_LABELS]}: {value}</p>)}{s.immediateAction&&<p><strong>Handoff action recorded:</strong> {s.immediateAction}</p>}</>}{a&&<><p>Assessment: {new Date(a.assessmentDate).toLocaleString("en-PH",{timeZone:"Asia/Manila"})}</p><p>Sex: {a.sex} · Civil status: {a.civilStatus} · Employment: {a.employment}</p><p>Address: {a.address||"Not recorded"}</p><p>Existing conditions: {a.conditionsAssessed?(a.conditions.join(", ")||"None reported"):"Not assessed"}</p><p>First-degree family history: {a.familyAssessed?(a.familyHistory.join(", ")||"None reported"):"Not assessed"}</p><p>Tobacco: {a.tobacco} · Alcohol: {a.alcohol} · Binge drinking: {a.binge}</p><p>Weekly exercise target met: {a.exercise} · High-risk diet reported: {a.nutrition}</p><p>Height: {a.heightCm??"Not measured"} {a.heightCm?"cm":""} · Weight: {a.weightKg??"Not measured"} {a.weightKg?"kg":""} · BMI: {m.bmi??"Not calculated"}</p><p>Waist: {a.waistCm??"Not measured"} {a.waistCm?"cm":""}</p>{waistAboveReference(c)===true&&<p><strong>Above supplied waist reference:</strong> clinician review needed (male &gt;90 cm / female &gt;80 cm). This is a screening flag, not a diagnosis.</p>}</>}</div>;}
