import {test} from "node:test";
import assert from "node:assert/strict";
import {screeningSchema,parseSavedCases,referralFixtures,screeningMetrics,waistAboveReference,hasRedFlags,confirmAppointment,aiInput,demoSlots} from "../app/lib/workflow.ts";
const redFlags={chestPain:"No",breathing:"Not assessed",unconscious:"No",speech:"No",face:"No",weakness:"No"};
const screening={chiefComplaint:"BP assessment",urgency:"Routine",arm:"Left",medications:"Unknown",allergies:"Unknown",glucose:null,redFlags,assessment:{assessmentDate:new Date().toISOString(),sex:"Female",civilStatus:"Married",address:"Private home address",employment:"Self-employed",conditions:[],conditionsAssessed:false,familyHistory:[],familyAssessed:false,tobacco:"Not assessed",alcohol:"Not assessed",binge:"Not assessed",exercise:"Not assessed",nutrition:"Not assessed",heightCm:160,weightKg:64,waistCm:null}};
test("expanded assessment survives persistence with calculated BP and BMI",()=>{const base=referralFixtures()[0];const c={...base,age:52,screening:screeningSchema.parse(screening),readings:[{systolic:146,diastolic:92,measuredAt:base.screenedAt},{systolic:144,diastolic:90,measuredAt:base.screenedAt}]};const restored=parseSavedCases([c])[0];assert.deepEqual(restored.screening,c.screening);assert.deepEqual(screeningMetrics(restored),{bpCount:2,systolic:145,diastolic:91,bmi:25});assert.equal(waistAboveReference(c),null);assert.equal(waistAboveReference({...c,screening:{...c.screening,assessment:{...c.screening.assessment,waistCm:81}}}),true);assert.equal(parseSavedCases([{...c,age:17}]),null);assert.equal(parseSavedCases([{...c,readings:c.readings.slice(0,1)}]),null);assert.match(aiInput(c).history,/Not assessed/);assert.equal(aiInput(c).history.includes("Private home address"),false);});
test("positive red flags require handoff information and block routine appointment",()=>{const acute={...screening,redFlags:{...redFlags,speech:"Yes"}};assert.equal(screeningSchema.safeParse(acute).success,false);const s=screeningSchema.parse({...acute,assessment:undefined,urgency:"Emergency",immediateAction:"Physician contacted; immediate assessment requested."});const c={...referralFixtures()[0],screening:s};assert.equal(hasRedFlags(c),true);assert.throws(()=>confirmAppointment(c,[],demoSlots()[0],demoSlots(),"Doctor"),/immediate/);assert.equal(hasRedFlags(referralFixtures()[0]),false);});

test("expanded fields survive the existing database save RPC",async()=>{const {PGlite}=await import("@electric-sql/pglite");const {readFile}=await import("node:fs/promises");const db=new PGlite();try{await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);");await db.exec(await readFile(new URL("../supabase/setup.sql",import.meta.url),"utf8"));const base=referralFixtures()[0];const c={...base,age:52,screening,readings:[...base.readings,base.readings[0]]};await db.query("select * from public.vitality_save_case($1,$2::jsonb,$3)",[c.id,JSON.stringify(c),null]);const saved=await db.query("select payload from public.vitality_cases where id=$1",[c.id]);assert.deepEqual(parseSavedCases([saved.rows[0].payload])[0].screening,screening);}finally{await db.close();}});
