import test from "node:test";import assert from "node:assert/strict";
import {bedrockConfig,parseModelJson,recordedDraft,bedrockProblem} from "../app/lib/assistant-support.ts";
import {sameSubmission} from "../app/lib/same-submission.ts";
import {caseSaveError} from "../app/lib/case-save-error.ts";
import {aiInput,referralFixtures,validateDraft,savePlan,availableSlots,demoSlots} from "../app/lib/workflow.ts";
test("existing app model setting works; explicit disabled flag stays disabled",()=>{assert.equal(bedrockConfig({AWS_REGION:"ap-southeast-1",BEDROCK_MODEL_ID:"existing-profile",LOCAL_DEMO_AI_ENABLED:"true"}).model,"existing-profile");assert.equal(bedrockConfig({AWS_BEDROCK_MODEL_ID:"preferred",BEDROCK_MODEL_ID:"other"}).model,"preferred");assert.equal(bedrockConfig({BEDROCK_AI_ENABLED:"false",LOCAL_DEMO_AI_ENABLED:"true"}).enabled,false);});
test("AI parser accepts JSON fences but rejects prose and malformed JSON",()=>{assert.deepEqual(parseModelJson('```json\n{"summary":"x"}\n```'),{summary:"x"});assert.throws(()=>parseModelJson('Here is your diagnosis {"summary":"x"}'));});
test("fallback is factual, source-valid and cannot create a diagnosis or plan",()=>{const c=referralFixtures()[0],input=aiInput(c),draft=validateDraft(recordedDraft(input),input);assert.equal(draft.patientExplanation,"");assert.ok(draft.summary.includes(String(c.readings[0].systolic)));assert.deepEqual(draft.evidenceIds,["readings","history"]);assert.equal(c.outcome,null);});
test("repeated creation preserves progressed record; changed intake is not an identical submission",()=>{const c=referralFixtures()[0],next=savePlan(c,{action:"Review",destination:"Demo clinic",due:"2026-10-06T00:00:00Z",bring:"Records",contact:"Demo desk"},"Doctor");assert.ok(sameSubmission(c,next));assert.ok(!sameSubmission(c,{...c,name:"Different person"}));});
test("slot and identity conflicts are distinguished; raw provider details never exposed",()=>{assert.match(caseSaveError({code:"23505",message:'duplicate constraint "vitality_slot_unique"'}),/appointment time/);assert.match(caseSaveError({code:"23505",message:'duplicate constraint "vitality_cases_pkey"'}),/case ID/);assert.equal(bedrockProblem({name:"AccessDeniedException",message:"secret detail"}).code,"access_denied");assert.ok(!bedrockProblem({name:"AccessDeniedException",message:"secret detail"}).message.includes("secret detail"));});

test("appointment availability uses timestamps, not hospital display names or date spelling",()=>{const c=savePlan(referralFixtures()[0],{action:"Review",destination:"Older hospital label",due:"2026-10-06T09:00:00+08:00",bring:"Records",contact:"Desk"},"Doctor");assert.deepEqual(availableSlots([c],["2026-10-06T01:00:00.000Z","2026-10-06T02:00:00.000Z"],Date.parse("2026-10-04T00:00:00Z")),["2026-10-06T02:00:00.000Z"]);});

test("known approvedPlan citation maps to plan but invented citations still fail",()=>{const c=savePlan(referralFixtures()[0],{action:"Review",destination:"Demo clinic",due:"2026-10-06T00:00:00Z",bring:"Records",contact:"Desk"},"Doctor"),draft=recordedDraft(aiInput(c));draft.evidenceIds=["approvedPlan"];assert.deepEqual(validateDraft(parseModelJson(JSON.stringify(draft)),aiInput(c)).evidenceIds,["plan"]);draft.evidenceIds=["unknown_hospital_record"];assert.throws(()=>validateDraft(parseModelJson(JSON.stringify(draft)),aiInput(c)));});

test("three-day demo slots stay unique and chronologically ordered",()=>{const slots=demoSlots(Date.parse("2026-10-04T04:00:00Z"),3);assert.equal(slots.length,15);assert.equal(new Set(slots).size,15);assert.ok(slots.every((s,i)=>!i||Date.parse(s)>Date.parse(slots[i-1])));assert.equal(slots[0],"2026-10-05T01:00:00.000Z");assert.equal(slots.at(-1),"2026-10-07T06:00:00.000Z");});
