import test from 'node:test';
import assert from 'node:assert/strict';
import { fixtures, savePlan, updateStep, recordOutcome, closeCase, canClose, sourceOf, approveDraft, validateDraft, aiInput, summarize, parseSavedCases } from '../app/lib/workflow.ts';
import { RequestCache } from '../app/lib/request-cache.ts';

function active() { const c=fixtures()[0]; return savePlan(c,{action:'Demo clinic assessment',destination:'Demo RHU',due:new Date(Date.now()+3600000).toISOString(),bring:'Referral code; no other preparation specified.',contact:'Demo staff'},'Doctor'); }
const finalOutcome = {kind:'diagnosis_confirmed',diagnosis:'Fictional condition',explanation:'Simulated clinician assessment.',followUp:'Coordinate follow-up with staff.',followUpDue:new Date(Date.now()+86400000).toISOString()};
test('BHW cannot approve clinical plan or write diagnosis',()=>{assert.throws(()=>savePlan(fixtures()[0],{},'BHW'));assert.throws(()=>recordOutcome(active(),finalOutcome,'BHW'));});
test('patient report stays unconfirmed and cannot close episode',()=>{const c=updateStep(active(),'DEMO-001-attendance','Patient',true);assert.equal(c.steps[0].state,'reported');assert.equal(canClose(c),false);assert.throws(()=>closeCase(c,'Doctor'));assert.throws(()=>updateStep(c,'DEMO-001-assessment','Patient'));});
test('final outcome needs confirmed assessment; communication needs outcome',()=>{assert.throws(()=>recordOutcome(active(),finalOutcome,'Doctor'));assert.throws(()=>updateStep(active(),'DEMO-001-communication','Doctor'));});
test('required confirmations close assessment, ongoing follow-up stays open',()=>{let c=active();c=updateStep(c,'DEMO-001-attendance','BHW');c=updateStep(c,'DEMO-001-assessment','Doctor');c=recordOutcome(c,finalOutcome,'Doctor');assert.equal(canClose(c),false);c=updateStep(c,'DEMO-001-communication','Doctor');c=closeCase(c,'Doctor');assert.equal(c.status,'completed');assert.equal(c.steps.find(s=>s.kind==='follow_up').state,'pending');assert.equal(summarize([c]).openTasks,1);assert.throws(()=>updateStep(c,'DEMO-001-assessment','Doctor'));});
test('further assessment resets assessment confirmation and prevents closure',()=>{let c=updateStep(active(),'DEMO-001-assessment','Doctor');c=recordOutcome(c,{...finalOutcome,kind:'more_assessment_needed'},'Doctor');assert.equal(c.steps.find(s=>s.kind==='assessment').state,'pending');assert.equal(canClose(c),false);});
test('changed source prevents approval of stale AI draft',()=>{const c=active();c.draft={value:{summary:'Draft',patientExplanation:'Draft plan',missingFields:[],evidenceIds:['plan']},source:sourceOf(c),approved:false,latencyMs:100,cached:false};assert.equal(approveDraft(c,'Doctor').draft.approved,true);assert.throws(()=>approveDraft({...c,history:'Changed'},'Doctor'));assert.throws(()=>approveDraft(c,'BHW'));});
test('AI rejects unsupported source references and instructions without plan',()=>{const input=aiInput(fixtures()[0]);assert.throws(()=>validateDraft({summary:'Draft',patientExplanation:'Go to clinic',missingFields:[],evidenceIds:['plan']},input));assert.throws(()=>validateDraft({summary:'Draft',patientExplanation:'',missingFields:[],evidenceIds:['unknown']},input));assert.throws(()=>validateDraft({summary:'Draft',patientExplanation:'',missingFields:[],evidenceIds:[],newDiagnosis:'invented'},input));});
test('fixture counts are derived from recorded episodes',()=>{const s=summarize(fixtures());assert.equal(s.total,6);assert.equal(s.awaiting,1);assert.equal(s.completed,1);assert.equal(s.areas.reduce((n,a)=>n+a.total,0),6);});
test('corrupt persisted data is rejected; valid fixtures round trip',()=>{assert.equal(parseSavedCases([{id:'bad'}]),null);assert.equal(parseSavedCases(JSON.parse(JSON.stringify(fixtures()))).length,6);});
test('identical in-flight calls coalesce and completed result is cached',async()=>{const cache=new RequestCache(2,1000,1);let calls=0;let resolve;const p=cache.run('a',()=>{calls++;return new Promise(r=>resolve=r);});const q=cache.run('a',()=>{calls++;return Promise.resolve(2);});await Promise.resolve();resolve(1);assert.equal((await p).value,1);assert.equal((await q).value,1);assert.equal(calls,1);assert.equal((await cache.run('a',async()=>9)).cached,true);});
test('bounded concurrency rejects excess; failure allows later retry',async()=>{const cache=new RequestCache(2,1000,1);let resolve;const p=cache.run('a',()=>new Promise(r=>resolve=r));await Promise.resolve();await assert.rejects(cache.run('b',async()=>2),/BUSY/);resolve(1);await p;await assert.rejects(cache.run('bad',async()=>{throw Error('fail');}));assert.equal((await cache.run('bad',async()=>3)).value,3);});
test('LRU capacity evicts old entries',async()=>{const cache=new RequestCache(1,1000,1);await cache.run('a',async()=>1);await cache.run('b',async()=>2);assert.equal((await cache.run('a',async()=>3)).cached,false);});
