import {z} from "zod";
import {authClient,staffAccess} from "@/app/lib/staff-auth";
import {database} from "@/app/lib/db";
import {json,localRequest,readJson} from "@/app/lib/local-api";
export const runtime="nodejs";
const email=z.string().trim().toLowerCase().email().max(150),password=z.string().min(8).max(128);
const input=z.discriminatedUnion("action",[z.object({action:z.literal("login"),email,password}).strict(),z.object({action:z.literal("signup"),email,password,name:z.string().trim().min(1).max(100),role:z.enum(["BHW","Doctor"])}).strict()]);
export async function GET(request:Request){if(!localRequest(request))return json({error:"Use the app address."},403);const access=await staffAccess();if(access.denied){if(access.denied.status===401)return json({user:null});return access.denied;}return json({user:access.user});}
export async function POST(request:Request){if(!localRequest(request,true))return json({error:"Refresh the app and retry."},403);try{const value=input.parse(await readJson(request,5000)),auth=await authClient();if(value.action==="signup"){const result=await auth.auth.signUp({email:value.email,password:value.password,options:{emailRedirectTo:(process.env.APP_ORIGIN||`${process.env.VERCEL==="1"?"https:":new URL(request.url).protocol}//${request.headers.get("host")}`)+"/login"}});if(result.error)return json({error:result.error.message},400);if(result.data.user){const saved=await database().from("vitality_staff").upsert({auth_user_id:result.data.user.id,email:value.email,name:value.name,role:value.role,approved:false},{onConflict:"auth_user_id",ignoreDuplicates:true});if(saved.error&&result.data.session)return json({error:"Account created, but staff registration failed. Contact the administrator."},503);}await auth.auth.signOut();return json({pending:true,message:"Check your email to confirm your account, then ask the administrator to approve your staff access."});}
 const result=await auth.auth.signInWithPassword({email:value.email,password:value.password});if(result.error)return json({error:"Email or password is incorrect, or the email is not confirmed."},401);const access=await staffAccess();if(access.denied){await auth.auth.signOut();return access.denied;}return json({user:access.user});
 }catch(e){return json({error:e instanceof z.ZodError?"Enter a valid email and a password of at least 8 characters.":"Authentication service unavailable."},e instanceof z.ZodError?400:503);}}
export async function DELETE(request:Request){if(!localRequest(request,true))return json({error:"Refresh the app and retry."},403);try{const auth=await authClient(),result=await auth.auth.signOut();if(result.error)throw result.error;return json({ok:true});}catch{return json({error:"Could not sign out. Try again."},503);}}
